site_name: ApuJar
copyright: '© 2024 Dominic R. (aka. BlockyDotJar)'

theme:
  custom_dir: overrides
  favicon: assets/images/logo-apu.png
  features:
    - navigation.instant
    - navigation.tabs
    - toc.integrate
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
  name: material
  logo: assets/images/logo-apu.png
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: green
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: green
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
use_directory_urls: false

plugins:
  - search
  - redirects:
      redirect_maps:
        'oauth2/spotify.md': 'https://accounts.spotify.com/authorize?client_id=3afe9abbb2bd4c51bf9840c72ee76950&redirect_uri=https%3A%2F%2Fapujar.blockyjar.dev%2Foauth2%2Fspotify%2Fcallback.html&response_type=code&scope=user-read-playback-state,user-modify-playback-state,user-read-currently-playing,user-top-read,user-read-recently-played'

extra_css:
- 'assets/stylesheets/frontpage.css'
- 'assets/stylesheets/tasklists.css'

markdown_extensions:
  - admonition
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - footnotes
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

watch:
  - overrides

nav:
  - General:
    - Add Bot: general/add-bot.md
    - Part Bot: general/part-bot.md
    - Credits: general/credits.md
    - License: general/license.md
    - Dependencies: general/dependencies.md
  - Commands:
    - Owner Commands: commands/owner.md
    - Admin Commands: commands/admin.md
    - Utility Commands: commands/utility.md
    - Modscanner Commands: commands/modscanner.md
    - Spotify Commands: commands/spotify.md
    - 7tv Commands: commands/seventv.md
    - Weather Commands: commands/weather.md
    - Game Commands: commands/games.md
  - Spotify: oauth2/spotify.md
