name: build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-redirects
      - run: mkdocs gh-deploy --force
